config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :messages, only: [:new, :create]
  resources :home, only: [:index] do
    collection do
      post :import
      get :my_files
      get :clear_notifications
    end
  end
  root to: "home#index"
  mount ActionCable.server => '/websocketier'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  has_one_attached :excel_file
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  scope :read, -> { where(read: true) }
  scope :unread, -> { where(read: false) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable, :trackable, :lockable
  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }, presence: true, uniqueness: {case_sensitive: false}
  # belongs_to :managed_by, class_name: 'User', optional: true
  has_many :invitations, :class_name => self.to_s, :as => :invited_by
  has_many :file_uploads, foreign_key: :created_by_id
  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :filter_params, only: :import
  before_action :set_notifications, except: [:import]
  def index
    @excel_upload = current_user.file_uploads.build
  end

  def import
    if @file.nil?
      redirect_to request.referrer, notice: "No file provided!"
      return
    end
    import_file = FileUpload.new(
      excel_file: @file,
      file_name: @file.original_filename,
      created_by: current_user
    )
    if import_file.save!
      ProcessCsvUploadJob.perform_async(import_file.id, current_user.id)
      flash[:success] = "Upload successful"
    end
  end

  def my_files
    @files = current_user.file_uploads
  end

  def clear_notifications
    @unread_notifications.update_all(read: true)
    render json: {success: true}, status: 200
  end

  private

  def filter_params
    @file = params[:file_upload][:excel_file]
  end

  def set_notifications
    @unread_notifications = current_user.notifications.where(read: false)
  end

end

app/controllers/user_controller.rb
class User::InvitationsController < Devise::InvitationsController

  def index

  end


  private
    # This is called when creating invitation.
    # It should return an instance of resource class.
    def invite_resource
      # skip sending emails on invite
      super { |user| user.skip_invitation = true }
    end

    # This is called when accepting invitation.
    # It should return an instance of resource class.
    def accept_resource
      resource = resource_class.accept_invitation!(update_resource_params)
      # Report accepting invitation to analytics
      # Analytics.report('invite.accept', resource.id)
      resource
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.haml
.row
  .col-sm-12
    = form_for @excel_upload, url: import_home_index_path, remote: true do |f|
      .row
        .col-sm-4
        .col-sm-4
          .form-group
            = f.hidden_field :name, value: nil
            = f.file_field :excel_file, accept: 'text/csv',  class: "form-control"
            = f.submit 'Import', class: 'btn btn-primary mt-4'

= render 'shared/notification_modal', unread_notifications: @unread_notifications

:javascript
  $(document).ready(function() {

    $('#modal-button').click(function(){
      $('#notification-modal').modal('show');
    })

    $('.modal-close').click(function(){
      $('#notification-modal').modal('hide');
      $.ajax({
        type: 'GET',
        url: '/home/clear_notifications',
        dataType: "json",
        contentType: "application/json; charset=utf-8",
        success: function (data) {
          $('#notification-list').html('')
          $('#notification-count').html(0)
        }
      });
    })

    $('#new_file_upload').on('ajax:success', function(e, data, status, xhr){
      $('#file_upload_excel_file').val(null)
      alert('File uploaded');
    }).on('ajax:error',function(e, xhr, status, error){
      alert('Failed to upload');
    });
  })

app/views/home/my_files.html.haml
%div
  .row
    = link_to 'Back', home_index_path, class: 'float-left'
  .row
    .col-md-4
      %ul.list_group
        - @files.each do |file|
          %li
            %p
              = file.file_name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Harman
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8TQ5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", rel: "stylesheet"}
    %script{crossorigin: "anonymous", integrity: "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", src: "https://code.jquery.com/jquery-3.2.1.slim.min.js"}
    %meta{content: "width=devise-width, initial-scale=1, maximum-scale=1", name: "viewport"}/
    %script{src: "https://code.jquery.com/jquery-3.2.1.min.js"}

    %nav.navbar.navbar-dark.bg-dark.navbar-expand-lg
      %a.navbar-brand{href: "/", style: "padding: 10px"} Harman
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", type: "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse.justify-content-end
        - if user_signed_in?
          #current_user{'data-user-id': current_user.id}
          = link_to  my_files_home_index_path do
            .btn.btn-secondary
              My Files
          %button.btn#modal-button
            %span{style: "color: white;"}
              Notifications
            %span{style: "color: red;"}
              #notification-count
                = @unread_notifications.length
          %div{style: "padding: 10px;"}
            = link_to 'Log Out', destroy_user_session_path, class: "btn btn-outline-danger", method: :delete
        - else
          %div{style: "padding: 10px"}
            = link_to 'Login', new_user_session_path, class: "btn btn-outline-primary", :method => 'post'
          %div{style: "padding: 10px"}
            = link_to 'Join', new_user_registration_path, class: "btn btn-outline-success"
  %body
    - if user_signed_in?
      / <div style="float: right; padding-top: 10px; padding-right: 10px">
      / </div>
    %p.notice{style: "text-align: center;"}
      = notice
    %p.alert{style: "text-align: center;"}
      = alert
    .container-fluid{style: "text-align: center;"}
      = yield

app/views/shared/_excel_upload.html.haml
= form_for @excel_upload, url: import_path do |f|
  .row
    .col-sm-12
      .form-group
        = f.label :body
        = f.text_area :body, class: "form-control"
      .form-group
        = f.label :excel_file
        = f.file_field :excel_file, class: "form-control"
  .actions
    = f.submit 'Save'

app/views/shared/_notification_modal.html.haml
#notification-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "notificationModal", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-dialog-centered{role: "document"}
    .modal-content
      .modal-header
        %h5.modal-title Notifications
        %button.modal-close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .row
          .col-md-4
            %ul#notification-list
              - unread_notifications.each do |n|
                = n.message

app/views/users/invitations/edit.html.erb
<h2><%= t "devise.invitations.edit.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "users/shared/error_messages", resource: resource %>
  <%= f.hidden_field :invitation_token, readonly: true %>

  <% if f.object.class.require_password_on_accepting %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t("devise.invitations.edit.submit_button") %>
  </div>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "users/shared/error_messages", resource: resource %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="field">
      <%= f.label field %><br />
      <%= f.text_field field %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit t("devise.invitations.new.submit_button") %>
  </div>
<% end %>